---

- name: configure tomcat8
  hosts: all
  tasks:
          - name: install tomcat8
            apt:
                    name: tomcat8
                    state: present
          - name: copy tomcat-users.xml file
            copy:
                    src: /home/ubuntu/newfile1
                    dest: /etc/tomcat8
          - name: change port of tomcat from 8080 to 9090
            replace:
                    regexp: 8080
                    replace: 9090
                    path: /etc/tomcat8/server.xml
          - name: restart tomcat8
            service:
                    name: tomcat8
                    state: restarted
          - name: check url response of server 1
            uri:
                    url: http://172.31.9.38:9090
          - name: check url response of server 2
            uri:
                    url: http://172.31.0.248:9090

...


